services:
  api:
    build:
      context: ./api
    env_file: ./api/.env.production
    ports:
      - "${PORT}:${PORT}"
  realtime:
    build:
      context: ./realtime
    env_file: ./realtime/.env.production
    ports:
      - "${WS_PORT}:${WS_PORT}"
