services:
  redis:
    ports: []

  api:
    env_file: ./api/.env.production
    ports:
      - "80:${PORT}"

  realtime:
    env_file: ./realtime/.env.production
    ports:
      - "443:${WS_PORT}"

  worker:
    env_file: ./worker/.env.production