services:
  redis:
    image: redis:7
    container_name: lavi-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - lavi_backend

  api:
    container_name: lavi-api
    build:
      context: ./api
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - lavi_backend

  realtime:
    container_name: lavi-realtime
    build:
      context: ./realtime
    environment:
      - API_ADDR=http://api
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      api:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - lavi_backend

  worker:
    container_name: lavi-worker
    build:
      context: ./worker/
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - WS_ADDR=realtime
      - WS_PORT=${WS_PORT}
    depends_on:
      redis:
        condition: service_healthy
      realtime:
        condition: service_started

volumes:
  lavi_data:

networks:
  lavi_backend:
    name: lavi_backend
    driver: bridge
