services:
  database:
    container_name: lavi-postgres
    image: postgres:16
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=lavi_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - lavi_data:/var/lib/postgresql/data

  redis:
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  api:
    env_file: ./api/.env.development
    ports:
      - "${PORT}:${PORT}"

  realtime:
    env_file: ./realtime/.env.development
    ports:
      - "${WS_PORT}:${WS_PORT}"

  worker:
    env_file: ./worker/.env.development

volumes:
  lavi_data:

networks:
  lavi_backend:
    name: lavi_backend
    driver: bridge
